# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Find permutation candidates for each row
#' @param dates Vector of dates
#' @param unit_id Integer vector of individuals' ids (to avoid matching with
#' self).
#' @param incident_id Integer vector of the corresponding incident (to avoid
#' matching to the same incident).
#' @param ematch Integer matrix of variables over which exact match is desired.
#' @param window Integer scalar. Number of units of time to consider when
#' identifying candidates (see details)
#' @details
#' For each row `i` in the data, a row `j` is a possible permutation candidate if:
#' - `abs(date[i] - date[j]) <= window`,
#' - `unit_id` are different,
#' - `incident_id` are different, and
#' - `all(ematch[i, ] == ematch[j,])`
#' @returns
#' A list of integer vectors (starting from zero) indicating the position of
#' the potential permutation.
#' @export
#' @useDynLib njforce, .registration = TRUE
#' @importFrom Rcpp sourceCpp
find_candidates <- function(dates, unit_id, incident_id, ematch, window) {
    .Call(`_njforce_find_candidates`, dates, unit_id, incident_id, ematch, window)
}

#' Random permutation of the data as a function of `find_candidates`
#' @param candidates An integer list as that resulting from [find_candidates()].
#' @returns
#' An integer vector (indexed from 0) with the permuted version of the data.
#' @export
permute <- function(candidates) {
    .Call(`_njforce_permute`, candidates)
}

