# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Find permutation candidates for each row
#' @param features An integer matrix of features to be match (depending on
#' the window).
#' @param window An integer vector with length equal to the number of columns
#' in `features`.
#' @details
#' Matches (or permutation candidates) are identified depending on the rule
#' specified by `window`. For feature `k`, the match between `(i,j)` is possible if
#'
#' - If `window[k] < 0` and `features[i, k] != features[j, k]`
#' - If `abs(features[i, k] - features[j, k]) <= window[k]`
#'
#' @returns
#' A list of integer vectors (starting from zero) indicating the position of
#' the potential permutation.
#' @export
#' @useDynLib njforce, .registration = TRUE
#' @importFrom Rcpp sourceCpp
find_candidates <- function(features, upper, lower, as_abs) {
    .Call(`_njforce_find_candidates`, features, upper, lower, as_abs)
}

#' Random permutation of the data as a function of `find_candidates`
#' @param candidates An integer list as that resulting from [find_candidates()].
#' @returns
#' An integer vector (indexed from 0) with the permuted version of the data.
#' @export
permute <- function(candidates) {
    .Call(`_njforce_permute`, candidates)
}

sim_events_cpp <- function(nevents, nofficers, min_per_event = 1L, max_per_event = 5L, min_year = 0L, max_year = 10L, min_rate = 5L, max_rate = 5L, par_officer_female = -.5, par_officer_years = -.5, par_exposure_event = 0, par_exposure_prev = .5, par_event_violence = 1.0, par_officer_fe = 1.0, nsims = 1L, seed = 123L) {
    .Call(`_njforce_sim_events`, nevents, nofficers, min_per_event, max_per_event, min_year, max_year, min_rate, max_rate, par_officer_female, par_officer_years, par_exposure_event, par_exposure_prev, par_event_violence, par_officer_fe, nsims, seed)
}

sim_events2_cpp <- function(event_id, officer_id, officer_female, officer_rate, officer_fe, officer_years, par_officer_female, par_officer_years, par_exposure_event, par_exposure_prev, par_event_violence, par_officer_fe, nsims, seed) {
    .Call(`_njforce_sim_events2`, event_id, officer_id, officer_female, officer_rate, officer_fe, officer_years, par_officer_female, par_officer_years, par_exposure_event, par_exposure_prev, par_event_violence, par_officer_fe, nsims, seed)
}

