# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Find permutation candidates for each row
#' @param features An integer matrix of features to be match (depending on
#' the window).
#' @param window An integer vector with length equal to the number of columns
#' in `features`.
#' @details
#' Matches (or permutation candidates) are identified depending on the rule
#' specified by `window`. For feature `k`, the match between `(i,j)` is possible if
#'
#' - If `window[k] < 0` and `features[i, k] != features[j, k]`
#' - If `abs(features[i, k] - features[j, k]) <= window[k]`
#'
#' @returns
#' A list of integer vectors (starting from zero) indicating the position of
#' the potential permutation.
#' @export
#' @useDynLib njforce, .registration = TRUE
#' @importFrom Rcpp sourceCpp
find_candidates <- function(features, upper, lower, as_abs) {
    .Call(`_njforce_find_candidates`, features, upper, lower, as_abs)
}

#' Random permutation of the data as a function of `find_candidates`
#' @param candidates An integer list as that resulting from [find_candidates()].
#' @returns
#' An integer vector (indexed from 0) with the permuted version of the data.
#' @export
permute <- function(candidates) {
    .Call(`_njforce_permute`, candidates)
}

#' Simulate Police Force Events
#'
#' This function generates data similar to that featured in the paper. Events
#' are drawn at random, as the number of officers per event. The outcome variable,
#' whether the officer points his gun or not, is drawn sequentially as a poisson
#' process.
#'
#' @param nevents,nofficers Integers. Number of events and officers to simulate.
#' @param min_per_event,max_per_event Integers. Lower and upper bounds for the
#' number of officers in the event.
#' @param min_year,max_years Integers. Lower and upper bounds for the number
#' of years of experience of the officers.
#' @param min_rate,max_rate Doubles. Lower and upper bounds for the reaction
#' rates (see details).
#' @param female_par,years_par,rho_par,exposure_par Doubles. Parameters (coefficients) for
#' the logistic probabilities.
#' @param seed Integer. Seed for the pseudo-number generation.
#'
#' @details
#' The simulation process goes as follow:
#' 1. The officers are simulated. Female ~ Bernoulli(0.5),
#'    Action rate ~ Unif(min_rate, max_rate),
#'    Years of experience ~ Discrete Unif[min_years, max_year]
#' 2. Events are simulated, each event has a nofficers ~ Discrete Unif[min_per_event, max_per_event]
#'    Once the event is done, a sequence of reaction is given by each officers'
#'    action rate (Poisson process). Whether an officer points or not is set by
#'    a logistic model
#'
#'    point ~ female + years of experience + has any pointed? + previous exposure
#'
#'    The corresponding parameters are as specified by the user. Events are simulated
#'    one at a time.
#' @returns
#' A list of double vectors each with:
#' - Officer id
#' - Whether the officer is female
#' - Years of experience
#' - Incident id
#' - Whether the officer pointed a gun
#' The length of the list equals the number of reports.
#' @export
simulate_njforce <- function(nevents, nofficers, min_per_event = 1L, max_per_event = 5L, min_year = 0L, max_year = 10L, min_rate = 5L, max_rate = 5L, female_par = -.5, years_par = -.5, rho_par = 0, exposure_par = .5, seed = 123L) {
    .Call(`_njforce_simulate_njforce`, nevents, nofficers, min_per_event, max_per_event, min_year, max_year, min_rate, max_rate, female_par, years_par, rho_par, exposure_par, seed)
}

#' @export
#' @param incidentid,officerid Integer vectors. Values for the incident and
#' officer id.
#' @param female,years Logical and integer vectors, respectively. Features
#' of the officers.
#' @rdname simulate_njforce
#' @details
#' In the case of `simulate_njforce2`, the user can pass predefined events and
#' officers and use those to simulate each officers' reactions.
simulate_njforce2 <- function(incidentid, officerid, female, years, female_par, years_par, rho_par, exposure_par, seed) {
    .Call(`_njforce_simulate_njforce2`, incidentid, officerid, female, years, female_par, years_par, rho_par, exposure_par, seed)
}

